### ISSUE TITLE
I cannot find the reentrancy example in the folder of examples

### ISSUE THREAD

**Issue by Messi-Q** [gongbell/ContractFuzzer#1]
I cannot find the reentrancy example in the folder of examples. But in your paper, the vulnerability type contains the Reeantrancy. Can you give me an example about reeantrancy. If you can share the smart contract set, I will be very grateful.

**Comment by gongbell** [comment]
The examples are at 
https://github.com/gongbell/ContractFuzzer/tree/master/examples/reentrancy
