### ISSUE TITLE
Can't download ContractFuzzer's docker file

### ISSUE THREAD

**Issue by kimdora** [gongbell/ContractFuzzer#12]
Hello, I want to use the docker file of ContractFuzzer. But I can't download it because the file is on Baidu. Can you upload the docker file on GitHub?

And can you tell me how to measure coverage in ContractFuzzer? I want to compare with yours!

**Comment by Pindapinda** [comment]
Hi kimdora,
I had a samilar problem concerninig the docker but managed to download it and have uploaded it on [this](https://github.com/gongbell/ContractFuzzer/issues/8) issue.

**Comment by kimdora** [comment]
@Pindapinda ,Thank you for your help!
