### ISSUE TITLE
Cannot build nor download docker image

### ISSUE THREAD

**Issue by ezulkosk** [gongbell/ContractFuzzer#2]
When trying to build a docker image from source, it immediately fails due to an unknown dependency:

```
Sending build context to Docker daemon  3.105GB
Step 1/15 : FROM golang_nodejs:v1-ly
pull access denied for golang_nodejs, repository does not exist or may require 'docker login'
```

Is there a docker image that was not made public?

Further, the pre-built image hosted on Baidu is, as far as I can tell, not accessible to anyone without a Chinese phone number. Can this be hosted elsewhere?

**Comment by zqzqz** [comment]
The same error. 
Is it https://github.com/XBWer/SmartContract-Fuzzer for go_lang_nodejs:v1-ly?
It seems the repo includes all chain data, tmp files libraries and binaries, which causes to repo to be 3.4 GB. The large size troubles me a lot. No offense but I wonder really the author knows the usage of git?
Also, baidu service may not be proper for such a work published on the top conference.
Look forward to a reorganization. I am really interested in this work. Thanks!

**Comment by Danc2050** [comment]
Sorry, this will be a duplicate issue I filed [here](here).

**Comment by Zhongwenn** [comment]
Same error here.
`Step 1/15 : FROM golang_nodejs:v1-ly`

**Comment by Danc2050** [comment]
> Same error here.
> `Step 1/15 : FROM golang_nodejs:v1-ly`

@Zhongwenn If you change the line to what I mentioned above, it should work. There are still errors though.

**Comment by Zhongwenn** [comment]
@Danc2050 Thanks a lot. Changing the dockerfile did work. But I got another error. Do you have any ideas :)

`Adas-Macbook-Pro:ContractFuzzer ada$ docker build -t contractfuzzer .
Sending build context to Docker daemon  3.105GB
Step 1/15 : FROM agendolabs/golang_nodejs
latest: Pulling from agendolabs/golang_nodejs
e110a4a17941: Pull complete 
ac58758e6ad5: Pull complete 
8bc518271faa: Pull complete 
ed3b8113e4a5: Pull complete 
cb520cb37b0c: Pull complete 
ffcc1dbd196f: Pull complete 
03f4475b1546: Pull complete 
f3f8e2042e0a: Pull complete 
Digest: sha256:137e8b356439ee7b23bcb38ff9583c676913edde1c57d3eef69dcd35b697a7d8
Status: Downloaded newer image for agendolabs/golang_nodejs:latest
 ---> 87d32887bcea
Step 2/15 : MAINTAINER LIUYE, BUAA <1601695692@qq.com>
 ---> Running in ae2eca52c5d2
Removing intermediate container ae2eca52c5d2
 ---> a5ba797ce8bf
Step 3/15 : RUN mkdir -p /ContractFuzzer
 ---> Running in b83881d80ca3
Removing intermediate container b83881d80ca3
 ---> ef2868da42fb
Step 4/15 : WORKDIR /ContractFuzzer
 ---> Running in fa811da5de23
Removing intermediate container fa811da5de23
 ---> 4b560d853518
Step 5/15 : ADD go-ethereum-cf go-ethereum
 ---> 78167f3bf26a
Step 6/15 : ADD Ethereum Ethereum
 ---> a94a7d966bc2
Step 7/15 : ADD examples examples
 ---> eeafc6ae96b6
Step 8/15 : ADD contract_fuzzer contract_fuzzer
 ---> 142bd99f9d1b
Step 9/15 : ADD contract_tester contract_tester
 ---> 25d72e051755
Step 10/15 : ADD fuzzer_run.sh fuzzer_run.sh
 ---> 52e5b93f1499
Step 11/15 : ADD tester_run.sh tester_run.sh
 ---> cfd0333c347d
Step 12/15 : ADD geth_run.sh  geth_run.sh
 ---> ac36d4f61add
Step 13/15 : ADD run.sh  run.sh
 ---> 1cf8db368597
Step 14/15 : RUN   (cd go-ethereum && make geth)                                &&   (cd contract_fuzzer && source ./gopath.sh && cd ./src/ContractFuzzer/contractfuzzer && go build -o contract_fuzzer) &&   cp contract_fuzzer/src/ContractFuzzer/contractfuzzer/contract_fuzzer /usr/local/bin   &&   cp go-ethereum/build/bin/geth /usr/local/bin/                &&   apk del git  make gcc musl-dev linux-headers                 &&   rm -rf ./go-ethereum && rm -rf ./contract_fuzzer                 &&   rm -rf /var/cache/apk/*
 ---> Running in 0e960df60faf
/bin/sh: make: not found
The command '/bin/sh -c (cd go-ethereum && make geth)                                &&   (cd contract_fuzzer && source ./gopath.sh && cd ./src/ContractFuzzer/contractfuzzer && go build -o contract_fuzzer) &&   cp contract_fuzzer/src/ContractFuzzer/contractfuzzer/contract_fuzzer /usr/local/bin   &&   cp go-ethereum/build/bin/geth /usr/local/bin/                &&   apk del git  make gcc musl-dev linux-headers                 &&   rm -rf ./go-ethereum && rm -rf ./contract_fuzzer                 &&   rm -rf /var/cache/apk/*' returned a non-zero code: 127`

**Comment by Danc2050** [comment]
@Zhongwenn 
The Docker version they are using is alpine -- a minimal linux distribution. It does not normally have shell. To overcome this, add this line to line 20

```RUN apk add --update alpine-sdk && apk update```.

**Comment by Zhongwenn** [comment]
@Danc2050 
Finally, I succeeded. LoL.
Here is what I've done.

1st, `git pull` to get the newest version. I noticed that a Dockerfile was updated a few days ago.
2nd, find a stable network connection. I failed a lot of times because my office network is not friendly to download libs. After I switched to another WiFi, things got better.

Let me know if you have further questions.
Good luck :)

**Comment by Danc2050** [comment]
@Zhongwenn 
Hoorah! Glad you found this out. Looks like I was right with regards to the Go thing.

I am having an issue still though, if you have a moment to help.
The command:```docker build -t ContractFuzzer .``` is, I believe wrong, so I use the command ```docker build -t contract_fuzzer .```. However, I get neverending g++ compilations with error messages about functions "falling through". I don't think this is a network issue... did this happen to you? I can post a picture if this is unclear.

**Comment by imranashraf89** [comment]
@Danc2050 
The same thing happened with me. But I let it run nevertheless. After about 20 minutes or so.. it finally worked.
