### ISSUE TITLE
"deployer_run.sh" cannot exec well

### ISSUE THREAD

**Issue by Messi-Q** [gongbell/ContractFuzzer#3]
For that, deployer.sh cannot work. I cannot deploy a smart contract.

**Comment by DNXie** [comment]
I got the same problem. 

When I run `sh ./deployer_run.sh`

-> `./deployer_run.sh: line 2: bnode: not found`

**Comment by Franklinliu** [comment]
Sorry. I made the mistakes. 
Now I have updated  _deployer_run.sh_  file. Please have a try. Thank you!

**Comment by Franklinliu** [comment]
> I got the same problem. @gongbell
> 
> When I run `sh ./deployer_run.sh`
> 
> -> `./deployer_run.sh: line 2: bnode: not found`

Sorry. I made the mistakes.
Now I have updated deployer_run.sh file. Please have a try. Thank you!
