### ISSUE TITLE
wrong password for docker in BaiduNetDisk

### ISSUE THREAD

**Issue by ToolmanInside** [gongbell/ContractFuzzer#8]
the password `12ww` is wrong

**Comment by gongbell** [comment]
Updated again

Seems the problem with Baidu netdisk.

**Comment by xf97** [comment]
I once again encountered the password problem of Baidu netdisk (12ww)

**Comment by gongbell** [comment]
I am not sure of your problem. But I and my teammates  can access the
docker without any problem.

**Comment by Pindapinda** [comment]
I had the same problem until I copy-pasted the password that was provided in the documentation, that solved it for me.

**Comment by Pindapinda** [comment]
So I managed to download the contractfuzzer.tar file from Baidu Netdisk, which was pretty hard outside of China and I uploaded it on Google Drive for other people to use please check out [this link](https://drive.google.com/file/d/1WzIXIPCpZacu5MmNhWiCKn-6ukbUJyse/view?usp=sharing).

**Comment by gongbell** [comment]
Thanks.
