### ISSUE TITLE
How many Ethereum smart contract problems can ContractFuzzer detect now?

### ISSUE THREAD

**Issue by xf97** [gongbell/ContractFuzzer#9]
Hello, I am a graduate student from Hohai University. I've just read your paper, and I noticed that contractFuzzer can detect seven problems. What I am interested in is whether the types of problems contractFuzzer can detect have changed at the moment. I hope you can answer my questions.  I'm sorry to disturb you. I wish you a happy life.

**Comment by gongbell** [comment]
The types of smart contract of contract fuzzer has not changed, thanks.
